[package]
name = "merkle_toolkit"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
[[bench]]
name = "merkle"
harness = false

[dependencies.sha2]
version = "0.10.9"
[dev-dependencies.criterion]
version = "0.5"